export const dataDB = [

    {
        id: 1,
        name: "P1",
        urlImage: "./images/P1.jpeg",
        Stock: 7,
        price: 5,
    },
    {
        id: 2,
        name: "P11",
        urlImage:"/images/P11.jpeg",
        Stock:8,
        price: 7,
    },
    {
        id: 3,
        name: "P10",
        urlImage:"/images/P10.jpeg",
        Stock: 12,
        price: 8,
    },
    {
        id: 4,
        name: "P15",
        urlImage: "/images/P15.jpeg",
        Stock:15,
        price: 6,
    },
    /*
    {
        id: 5,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 6,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 7,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 8,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 9,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 10,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 11,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 12,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 13,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 14,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 15,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 16,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 17,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 18,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 19,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 20,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 21,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 22,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 23,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 24,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 25,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
    {
        id: 26,
        name: ,
        urlImage:,
        Stock:,
        price: ,
    },
*/


]